apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "graph_server.fullname" . }}
  labels:
    {{- include "graph_server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
            {{- include "graph_server.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "graph_server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: docker.io/ilfur/graphserver:1.0
          ports:
            - containerPort: 8080
              name: graphserver
          volumeMounts:
            - name: storagegv
              mountPath: /graph_server/webapps/gviz22
          volumeMounts:
            - name: storagerdf
              mountPath: /graph_server/webapps/orardf22
          volumeMounts:
            - name: storagegserv
              mountPath: /graph_server/webapps/gserv22
          imagePullPolicy: IfNotPresent
      volumes:
        - name: storagegv
          persistentVolumeClaim:
            claimName: graph-pvc01
        - name: storagerdf
          persistentVolumeClaim:
            claimName: graph-pvc02
        - name: storagegserv
          persistentVolumeClaim:
            claimName: graph-pvc03





