apiVersion: v1
kind: Service
metadata:
  name:  {{ include "graph_server.fullname" . }}
spec:
  selector:
   {{- include "cloudbeaver.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
