apiVersion: v1
kind: Service
metadata:
  name:  {{ include "ords.fullname" . }}
spec:
  selector:
      {{- include "ords.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8181
      name: ords
  type: {{ .Values.service.type }}
