apiVersion: v1
kind: Service
metadata:
  name:  {{ include "oml4py.fullname" . }}
spec:
  selector:
      {{- include "oml4py.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8888
  type: {{ .Values.service.type }}
