apiVersion: v1
kind: Service
metadata:
  name:  {{ include "oas.fullname" . }}
spec:
  selector:
      {{- include "oas.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.consoleport }}
      targetPort: 8080
      name: console
  type: {{ .Values.service.type }}
