apiVersion: v1
kind: Service
metadata:
  name:  {{ include "cloudbeaver.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "cloudbeaver.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8978
  type: {{ .Values.service.type }}
