# Please enter some details on what Oracle database to access
osa:
  connection: "hostname:port/service_name"
  # instead of entering passwords directly, please provide the name of a 
  # pre-defined secret and the key names to the passwords stored there.:
  secret:
    secretName: osa-secret
    newdbuserKey: newdbuser
    newdbpasswordKey: newdbpassword
    dbsysuserKey: dbsysuser
    dbsyspasswordKey: dbsyspassword

image:
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

