apiVersion: v2
name: radlaufstellen2
description: analytic software stack of machine learning database, masked data, jupyter, cloudbeaver

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "21.3.0"
icon: "https://www.berlin.de/imgscaler/Ptti0ihmnlMWc4y90gVkxZibnLgOuYNeRchIMyDCl8k/ropen/L3N5czExLXByb2Qvc2VuL3V2ay9fYXNzZXRzL3ZlcmtlaHIvdmVya2VocnNwbGFudW5nL3JhZHZlcmtlaHIvd2VpdGVyZS1yYWRpbmZyYXN0cnVrdHVyL3phZWhsc3RlbGxlbi11bmQtZmFocnJhZGJhcm9tZXRlci91cGxvYWRfXzg4NDMzODFiMGRhYzA2Nzc5YTczMWJlNjIyOTFkYWU2XzIxMDcyN19mYWhycmFkYmFyb21ldGVyXzE3MDAuanBn.jpg"
