apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "var.fullname" . }}
  labels:
    {{- include "var.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
            {{- include "var.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "var.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: {{ .Values.image.repository }}
          ports:
            - containerPort: 8978
              name: cloudbeaver
          volumeMounts:
            - name: storagebv
              mountPath: /opt/cloudbeaver/workspace
          imagePullPolicy: IfNotPresent
      initContainers:
        - name: volume-mount-permissions
          image: busybox
          command: ["/bin/bash" , "-c" , "curl https://raw.githubusercontent.com/DerRotMilan/VirtualAnalyticRooms/main/VARdata/credentials-config.json -o /opt/cloudbeaver/workspace/credentials-config.json && curl https://raw.githubusercontent.com/DerRotMilan/VirtualAnalyticRooms/main/VARdata/data-sources.json -o /opt/cloudbeaver/workspace/data-sources.json" ]
          volumeMounts:
          - name: storagebv
            mountPath: /opt/cloudbeaver/workspace
      volumes:
        - name: storagebv
          persistentVolumeClaim:
            claimName: cloudbeaver-pvc
