{{- if eq .Values.verrazzano.OAMdeploy false }}
apiVersion: v1
kind: Service
metadata:
  name:  {{ include "var.fullname" . }}-jupyter
  annotations:
    var/component: jupyter notebook
    var/name: raddauerzaehlstellen
    var/shortdesc: 'Anwendungs-Stack mit Datenbank, Analysedaten und Analysewerkzeug,
      hier: Fahrrad-Durchlaufzahlen'
  creationTimestamp: "2022-11-03T20:59:10Z"
spec:
  selector:
      {{- include "var.selectorLabels" . | nindent 6 }}
      component: jupyter
  ports:
    - port: 8889
      targetPort: 8889
      name: jupyter
  type: LoadBalancer
{{- else }}
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: {{ include "var.fullname" . }}-jupyter-svc-comp
spec:
  workload:
    apiVersion: v1
    kind: Service
    metadata:
      name:  {{ include "var.fullname" . }}-jupyter
      annotations:
        var/url: "http://{{ .Release.Name }}-cloudbeaver.{{ .Release.Namespace }}.{{ .Values.verrazzano.domainsuffix }}"
        var/component: jupyter notebook
        var/name: raddauerzaehlstellen
        var/shortdesc: 'Anwendungs-Stack mit Datenbank, Analysedaten und Analysewerkzeug,
          hier: Fahrrad-Durchlaufzahlen'
      creationTimestamp: "2022-11-03T20:59:10Z"
    spec:
      selector:
          {{- include "var.selectorLabels" . | nindent 10 }}
          component: jupyter
      ports:
        - port: 8889
          targetPort: 8889
          name: jupyter
{{- end }}

