{{- if eq .Values.verrazzano.OAMdeploy true }}
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: {{ include "var.fullname" . }}-cloudbeaver
  annotations:
    version: v1.0.0
    description: "Virtual Analytical Room Raddauerzaehlstellen"
spec:
  components:
    - componentName: {{ include "var.fullname" . }}-cloudbeaver-pvc-comp
    - componentName: {{ include "var.fullname" . }}-cloudbeaver-svc-comp
    - componentName: {{ include "var.fullname" . }}-cloudbeaver-comp
      traits:
        - trait:
            apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: {{ include "var.fullname" . }}-cloudbeaver-ingress
              annotations:
                kubernetes.io/ingress.class: istio
              spec:
                rules:
                  - host: {{ .Release.Name }}-cloudbeaver.{{ .Release.Namespace }}.{{ .Values.verrazzano.domainsuffix }}
                    http:
                      paths:
                        - path: "/"
                          backend:
                            serviceName: {{ include "var.fullname" . }}-cloudbeaver
                            servicePort: 8978
---
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: {{ include "var.fullname" . }}-jupyter
  annotations:
    version: v1.0.0
    description: "Virtual Analytical Room Raddauerzaehlstellen"
spec:
  components:
    - componentName: {{ include "var.fullname" . }}-jupyter-pvc-comp
    - componentName: {{ include "var.fullname" . }}-jupyter-svc-comp
    - componentName: {{ include "var.fullname" . }}-jupyter-comp
      traits:
        - trait:
            apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: {{ include "var.fullname" . }}-jupyter-ingress
              annotations:
                kubernetes.io/ingress.class: istio
              spec:
                rules:
                  - host: {{ .Release.Name }}-jupyter.{{ .Release.Namespace }}.{{ .Values.verrazzano.domainsuffix }}
                    http:
                      paths:
                        - path: "/"
                          backend: 
                            serviceName: {{ include "var.fullname" . }}-jupyter
                            servicePort: 8889
{{- end }}

