kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "var.fullname" . }}-scripts-config
data:
    testconn.sh: 
     "/opt/oracle/sqlcl/bin/sql /nolog << EOF \n
      whenever sqlerror exit failure; \n
      connect sys/$DB_PASSWORD@{{ .Values.database.hostname }}:1521/orclpdb1 as sysdba \n
      select * from dual; \n
      create table sys.dummymr0 ( c number ); \n
      exit; \n
      EOF \n
      if [ $? -eq 0 ] ; then echo \"connect successful\" ; else echo \"DB connect failed, waiting 2 mins and exiting...\" ; sleep 120 ; exit 5 ; fi"
    01_setPassword.sh: 
     "#!/bin/bash \n
      sqlplus / AS SYSDBA << EOF \n
      create table dummymr1( c number ); \n
      ALTER USER SYS IDENTIFIED BY \"$DB_PASSWORD\"; \n
      ALTER USER SYSTEM IDENTIFIED BY \"$DB_PASSWORD\"; \n
      ALTER SESSION SET CONTAINER=ORCLPDB1; \n
      ALTER USER PDBADMIN IDENTIFIED BY \"$DB_PASSWORD\"; \n
      ALTER SYSTEM SET ENABLE_DDL_LOGGING=TRUE; \n
      exit; \n
      EOF \n"
    02_setupOML.sh: 
     "#!/bin/bash \n
      sqlplus sys/$DB_PASSWORD@127.0.0.1/ORCLPDB1:1521 as sysdba << EOF \n
      ALTER PROFILE DEFAULT LIMIT PASSWORD_VERIFY_FUNCTION NULL; \n
      @/opt/oracle/product/21c/dbhome_1/oml4py/server/pyqcfg.sql \n
      exit; \n
      EOF \n"
    InitAll.sh: 
     "#!/bin/bash \n
      sqlplus / AS SYSDBA << EOF \n
      create table dummymr1( c number ); \n"
