kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "var.fullname" . }}-scripts-config
data:
    testconn.sh: "/opt/oracle/sqlcl/bin/sql /nolog << EOF \n
      whenever sqlerror exit failure; \n
      connect sys/$DB_PASSWORD@{{ .Values.database.hostname }}:1521/orclpdb1 as sysdba \n
      select * from dual; \n
      create table sys.dummymr01; \n
      exit; \n
      EOF \n
      if [ $? -eq 0 ] ; then echo \"connect successful\" ; else echo \"DB connect failed, waiting 2 mins and exiting...\" ; sleep 120 ; exit 5 ; fi"
