apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ include "var.fullname" . }}-job
  labels:
    {{- include "var.labels" . | nindent 4 }}
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: dbhelper
          image: docker.io/ilfur/oml4pydbhelper:latest
          command: [ "/bin/bash" , "/scripts/InitAll.sh" ]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_SID
              valueFrom: 
                secretKeyRef:
                  name: {{ include "var.fullname" . }}-secret
                  key: DB_SID
            - name: DB_PDB
              valueFrom: 
                secretKeyRef:
                  name: {{ include "var.fullname" . }}-secret
                  key: DB_PDB
            - name: DB_MEMORY
              valueFrom: 
                secretKeyRef:
                  name: {{ include "var.fullname" . }}-secret
                  key: DB_MEMORY
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: {{ include "var.fullname" . }}-secret
                  key: DB_PASSWORD
      initContainers:
        - name: dbcheck
          image: docker.io/ilfur/oml4pydbhelper:latest
          command: [ "/bin/bash", "/scripts/testconn.sh" ]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          env:
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: {{ include "var.fullname" . }}-secret
                  key: DB_PASSWORD
      volumes:
        - name: scripts
          configMap:
            name:  dbhelper-pvc


