apiVersion: v1
kind: Service
metadata:
  name:  {{ include "var.fullname" . }}-jupyter
spec:
  selector:
      {{- include "var.selectorLabels" . | nindent 6 }}
      component: jupyter
  ports:
    - port: 8889
      targetPort: 8889
      name: jupyter
  type: LoadBalancer

