kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "var.fullname" . }}-setup-config
data:
    01_setPassword.sh: "sqlplus / AS SYSDBA << EOF\n
    ALTER USER SYS IDENTIFIED BY \"$DB_PASSWORD\";\n
    ALTER USER SYSTEM IDENTIFIED BY \"$DB_PASSWORD\";\n
    ALTER SESSION SET CONTAINER=ORCLPDB1;\n
    ALTER USER PDBADMIN IDENTIFIED BY \"$DB_PASSWORD\";\n
    exit;\n
    EOF\n"
    02_setupOML.sh: "sqlplus sys/$DB_PASSWORD@127.0.0.1/ORCLPDB1:1521 as sysdba << EOF \n
     ALTER PROFILE DEFAULT LIMIT PASSWORD_VERIFY_FUNCTION NULL; \n 
     @/opt/oracle/product/21c/dbhome_1/oml4py/server/pyqcfg.sql \n
     exit;\n
     EOF\n"
