# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: {{ .Release.Name }}-cloudbeaver
  namespace: {{ .Release.Namespace }}
  annotations:
    version: v1.0.0
    description: "Cloudbeaver App"
spec:
  components:
    - componentName: {{ .Release.Name }}-cb-component
      traits:
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: IngressTrait
            metadata:
              name: {{ .Release.Name }}-dash-ingress
            spec:
              rules:
                - paths:
                    - path: "/ui"
                      pathType: Prefix


