apiVersion: core.oam.dev/v1alpha2
kind: ComponentSchematic
metadata:
  name: {{ include "var.fullname" . }}
spec:
  workload:
    apiVersion: apps/v1
    kind: Deployment
    spec:
      selector:
        matchLabels:
          {{- include "var.selectorLabels" . | nindent 8 }}
      replicas: {{ .Values.replicaCount }}
      template:
        metadata:
          labels:
            {{- include "var.selectorLabels" . | nindent 10 }}
        spec:
          containers:
            - name: app
              image: {{ .Values.image.repository }}
              ports:
                - containerPort: 8978
                  name: cloudbeaver
              volumeMounts:
                - name: storagebv
                  mountPath: /opt/cloudbeaver/workspace
              imagePullPolicy: IfNotPresent
          volumes:
            - name: storagebv
              persistentVolumeClaim:
                claimName: cloudbeaver-pvc
  parameters:
    - name: replicaCount
      description: Number of replicas for the deployment
      type: integer
      default: 1
    - name: image
      description: Docker image to use for the container
      type: object
      properties:
        repository:
          type: string
          default: {{ .Values.image.repository }}
      default:
        repository: {{ .Values.image.repository }}
    - name: pvc
      description: Persistent volume claim for the deployment
      type: object
      properties:
        name:
          type: string
          default: cloudbeaver-pvc
        accessModes:
          type: array
          items:
            type: string
          default:
            - ReadWriteOnce
        resources:
          type: object
          properties:
            requests:
              type: object
              properties:
                storage:
                  type: string
                  default: 10Gi
          default:
            requests:
              storage: 10Gi
