apiVersion: verrazzano.io/v1alpha1
kind: ComponentTrait
metadata:
  name: {{ include "var.fullname" . }}-cloudbeaver
spec:
  type: ingress
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: {{ .Values.service.host }}
        paths:
          - path: /cloudbeaver
            backend:
              serviceName: {{ include "var.fullname" . }}-cloudbeaver
              servicePort: {{ .Values.service.port }}
  parameters:
    - name: host
      description: The host name for the ingress
      type: string
      default: mydomain.com
    - name: port
      description: The port number to use for the service
      type: integer
      default: 80
    - name: type
      description: The type of the Kubernetes service
      type: string
      enum:
        - ClusterIP
        - NodePort
        - LoadBalancer
      default: ClusterIP
    - name: service
      description: The Kubernetes service definition
      type: object
      properties:
        port:
          type: integer
          default: 8978
      default:
        port: 8978
