apiVersion: v1
kind: Service
metadata:
  name:  {{ include "ggate.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "ggate.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 443
  type: {{ .Values.service.type }}
