bi:
  bi_rcu_dbconnect: 192.168.120.80:1521:orclpdb1
  bi_rcu_prefix: oas
  bi_admin_user: weblogic
  secret:
    secret_name: oas-secret
    bi_admin_pwd_key: bi_admin_pwd
    bi_rcu_sys_pwd_key: bi_rcu_sys_pwd

replicaCount: 1

image:
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  consoleport: 9500
  dvport: 9502

