apiVersion: v1
kind: Service
metadata:
  name:  {{ include "osa.fullname" . }}
spec:
  selector:
      {{- include "osa.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9080
      name: osa
  type: {{ .Values.service.type }}
